apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cron
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cron
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - echo $(date); echo "hello"
            image: busybox
            name: cron
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
