---
apiVersion: v1
kind: Secret
metadata: 
  name: nginxsecret
type: kubernetes.io/tls
data:
  # base64 encoded string
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lVY3lDS1dvdlYwU3pzcWlJSDAreUdrcEtkRCtrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERU9NQXdHQTFVRUF3d0ZibWRwYm5neERqQU1CZ05WQkFvTUJXNW5hVzU0TUI0WERUSXdNRFV4T1RFMApORFUwTVZvWERUSXhNRFV4T1RFME5EVTBNVm93SURFT01Bd0dBMVVFQXd3RmJtZHBibmd4RGpBTUJnTlZCQW9NCkJXNW5hVzU0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzM2lQOWxHTStWVE8KdHJzWDdDNm9adytsUGRBZlhpcWdVL0hvWThIU3BCNUJHU3ZGdzJ0NnRTSTJpdjllWFBvMjRSamp1UU11UyszVwoxVkRQS1NEUnhJSENMRitTM1J2UzhjSEF4K2RkTHp0d1lra2NlN29HNlpiY3NoSm9WbE5QbEU0bE9IL3lGcEtBCi9odUxtYkN6YnZ4b3FsZ0gzYmJ4M3g2amZFN05vTm9qZFl5VnRLZlNKT2JDai85MGlsc2ZoS0VZcUNXakpITUEKS1B0Q2xOZGNQS0lRZEVLUENPdE55VzFyNFZ3SXlzVmsySTA4bm55Rnp0UThIVFlSQ213d1J6N205ZG56am5FNApndmp6M01yYmZDdEkvNmVldkFKZHR5ZkQ3bUcrVVNVRE1BdjVwd2tOT3gzV0hhWjBHS1A5WE80djRaQ3BMVk9iCmhlaWY3cHdsZ3dJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVVJ1aUE4WGxDTllkaHBhc0RIRWZOTVhveU56b3cKSHdZRFZSMGpCQmd3Rm9BVVJ1aUE4WGxDTllkaHBhc0RIRWZOTVhveU56b3dEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQlQ5bDhjdEFTTHhBNTJOeEVXMUlobmJML1RIU0UwV2pJZGIvCjFUemQ4b1JIREJ0Qjg2bG9iMzhIQzkwZGtkR0xwTUhTcVNTOWJCTjd4ZTBTZDE0YTZVODBsbUYvRXoyUFYxZTgKOUlySmhEdFpQMDJFSDJRMFVzODl5S0h3ZmRCM0tCc1kzdXoyMHBYOVdVVHdCODNwcjh0Y2FXYkdwYmdtYmphRQp2WjBHd3FuVE1xczI5ZHlmaHVnMjVCNENzbVByMkZuM29ITG00cElsN2JBeGRyVy9nMlBvV2hsazVvbVo2SkdsCjNWTUd4RHF0UDFOZ3RXeWJlcVNldHNlSGp2RGtiaVdXV0tncmQ2RDRPS2MyUEdad0Q3NFRNS2JnRkRzR0lXcnYKN2wxQUhwZTRDZlFaVUZzWnZ2TWY0d2lKQXBEY0s0Y0xWRnd4MlQyTEF1ZFA4ZDBJSUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGZlSS8yVVl6NVZNNjIKdXhmc0xxaG5ENlU5MEI5ZUtxQlQ4ZWhqd2RLa0hrRVpLOFhEYTNxMUlqYUsvMTVjK2piaEdPTzVBeTVMN2RiVgpVTThwSU5IRWdjSXNYNUxkRzlMeHdjREg1MTB2TzNCaVNSeDd1Z2JwbHR5eUVtaFdVMCtVVGlVNGYvSVdrb0QrCkc0dVpzTE51L0dpcVdBZmR0dkhmSHFOOFRzMmcyaU4xakpXMHA5SWs1c0tQLzNTS1d4K0VvUmlvSmFNa2N3QW8KKzBLVTExdzhvaEIwUW84STYwM0piV3ZoWEFqS3hXVFlqVHllZklYTzFEd2ROaEVLYkRCSFB1YjEyZk9PY1RpQworUFBjeXR0OEswai9wNTY4QWwyM0o4UHVZYjVSSlFNd0MvbW5DUTA3SGRZZHBuUVlvLzFjN2kvaGtLa3RVNXVGCjZKL3VuQ1dEQWdNQkFBRUNnZ0VBWEZDUW4vK0dUZ1Z6czFiTWhodXNJNDc2QXZQejBWR29rNlR1REMrb1ZYWE8KREpqaGhGM2svZWlaUVloR3NnQUhKYXZEZnMxS2xjRTFxejlMcE1EVEJ1dFhqRDhiQzA0UU1TQ0tBOHFXMndraAozdWcyNVFHdkUxWG42NFBoS0RBWVFycVpjNktmSGlYOU5YdXBpcDdOTVA4Q09jUk4wNUJja0lBMnB3Wml1Wnc5CnhlN2kvUjgrekNFS0NWVkdzTzc4VnNFN2VrNEdFWDhyaGcrai9Iek8ySCt2OVVhL1pVN1FLMjBwU3pPSUtKd0QKYmpTQkFkZHV0NWFiVVd5andpb3NyRVNCTUQ4OG12WHZXT3lpb0RYQUtLNVVlZVBiZ1dzRmRGcEdudndiaDF2bwppcmFPVi9CQit4ak5aUWljekw5MUdacnBBZEtLQnNkQXZFQklNb3I3MlFLQmdRRHdhK2ZsbnRpRjBaOGVtc0t2ClVIMi95RHpNT3c3Y05seHBYdzVtRHhlcE9kTjFWMTRFZ3ZwQnduMFFOUVk2dVJhdXRiQ1RxOTdaY2NBNUJBaVoKN3FtTXhXNllVdmlqNnRhMytiTERyM2RuZjUwMSthVXYvWWJhSGJZb3I3WUFnc3kwWXFzcUY4WFdDZkhnbFRYNApQNGR1ZzhmRnJlMmZMYTEvc2huUkpDb1pwUUtCZ1FEdDgzdGJWT3ovKy9KUmM1cHd3NGxXTUJreWpMYmFUTjlBCnVBWU5NTnNHRVo2VE10ZTdQNytVSFVlMGZUbzZaUXRRR0dlQ05Cemx1UlRIWnlIdjBLY1JHTkt2aldIL2Y1SkYKeE4vK0wySkI3cXRJT3RZb0FIT1FGazFmSVk4RTJuYWJBdFRmUlVydXNMSTg2R04wZ2NQTCtIOE82clVxMzdSQwpaSzZIenBFS0J3S0JnUURHMkxpSDFnVkhTTVRPVHpuT1BraURJbDRHbktJQnlJUk9NbXg2Uk9sUThaN1BZbDlFClpBQVArNGZzcTY1blMwWlRZYnFWcUlVOFd6U2M4NVVabTZkbjRyTkNFUDNNdFNLNkx5K0hZY3prTVV3WnBFelgKa0Z6RWNlYURhRENqNDRyamR1Z1NmRzhJUkZsbFlvT3N1djZNalRuaGFhVXJEbUI5U1JUSlFad0FjUUtCZ0JkQQpaNWx4SHdlVWt3VXFpcmppSXBWdGRjamV2eTl0dTVNVGFHUDVsaTF0bzFVMjdxVzVnUHIwTVlHTml4Y1JzSjFQCkJTNVA4Vkx4VnZwMU5YZTlwOVdmMjFhVU5qTkZRQUhaVHhvRGYxSjZBL3EyNVI1YmpPOVRmcFFCTDN5RjdIa1IKT2NQbmZYNzlmUzArZUJsMlpLK1Z4TFNzY3ErUjFJZDRWeVdtSmI0WkFvR0JBTldGUzNlQkZBNlF0KzYwOTJvWAp3NW02Ti9kZ3A0RTIxYTdTcllhVFd3UzZEQzczeS84SkdINGRMOHJpQ1NaclFGYmdKbDNXWVNoZHJHazEwNkFGCkVqWElSclFzNlNGSDhZdDlXc0VQcDhvUjM1R2VaZld4LzlSaXhaNWw0VTdON0RWaExiTlJUTUhyMFpBTGpxTHoKY3cyL2Vodk56U1VIS1doL2JJblRLdTJICi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1 # kubectl api-versions
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    # recommended labels
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: "1.14.2"
    app.kubernetes.io/component: proxy
    environment: production
spec: # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#deploymentspec-v1-apps
  selector: # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#labelselector-v1-meta
    matchLabels:
      app: nginx
  replicas: 10
  strategy: 
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  template: # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podtemplatespec-v1-core
    metadata: # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#objectmeta-v1-meta
      labels:
        app: nginx
    spec: #https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podspec-v1-core
      containers:
      - image: bprashanth/nginxhttps:1.0
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
      volumes:
      - name: configmap-volume
        configMap: 
          name: nginxconfigmap
      - name: secret-volume
        secret: 
          secretName: nginxsecret
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-network-policy
spec:
  podSelector: {} # match all pods
  ingress: [{}]
  policyTypes:
  - Ingress
